### ISSUE TITLE
broken on new 2ds 

### ISSUE THREAD

**Issue by Trickiy** [Cracko298/MC3DS-AWG#2]
When I install the mod and load the world I will spawn in the air and fall to my death in what looks like a super flat world.

**Comment by Cracko298** [comment]
Sorry to hear you're having trouble with the World Generation.
Which version of the mod are you currently running, along with the Version of the Game.

There is a bug that creates flat terrain, but it shouldn't be all flat world.
If you can, load the game into Creative, and send a screenshot of what the world looks like.

**Comment by Trickiy** [comment]
I am on the latest version of Minecraft(edit: digital not cartridge) and latest version of the mod. 
![image](https://github.com/Cracko298/MC3DS-AWG/assets/86691033/31999d56-2cca-43dc-ae8e-7a87b5e74695)

**Comment by Cracko298** [comment]
Those pillars show me the mod is working somewhat correctly. It might just be the spawn position itself rather than anything else. I'll see what I can do.

**Comment by Cracko298** [comment]
Sorry about the long wait, what where the coordinates you spawn at, it should be consistent(ish)

**Comment by Cracko298** [comment]
## Issue is now Fixed.
- Changed Compiler/Decompiler.
- Reworked some World Generation.
- Fixed Instakill Spawn Bug
